# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "pins-r")
v <- vetiver_pin_read(b, "inflazione_lm", version = "20240519T093057Z-793cd")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
